yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'


urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.TechView.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_post, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.handler500'

yatube/templates/includes/card_author.html
{% load thumbnail %}
<article>
  <ul>
    <li>
      Автор: {% if post.author.get_full_name %}
               {{ post.author.get_full_name }}
             {% else %}
               {{ post.author }}
             {% endif %}
      <br>
      <a href={% url 'posts:profile' post.author %}>все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
      <p>{{ post.text }}</p>
      <a href={% url 'posts:post_detail' post.id %}>подробная информация</a>
</article>
{% if post.group %}
  <a href={% url 'posts:group_list' post.group.slug %}>все записи группы</a>
{% endif %}
{% if not forloop.last %}<hr>{% endif %}

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>
  

yatube/templates/includes/header.html
<header>
{% load static %}
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href={% url 'posts:index' %}>
        <img src={% static 'img/logo.png' %} width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav">
        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:about' %}active disabled{% endif %}" href={% url 'about:author' %}>Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active disabled{% endif %}" href={% url 'about:tech' %}>Технологии</a>
        </li>
        {% if name %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'posts:post_create' %}active disabled{% endif %}" href={% url 'posts:post_create' %}>Новая запись</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:logout' %}active disabled{% endif %}" href={% url 'users:logout' %}>Выйти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:password_change_form' %}active disabled{% endif %}" href={% url 'users:password_change_form' %}>Изменить пароль</a>
        </li>
        {% endif %}
        {% if not name %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:signup' %}active disabled{% endif %}" href={% url 'users:signup' %}>Регистрация</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:login' %}active disabled{% endif %}" href={% url 'users:login' %}>Войти</a>
        </li>
        {% endif %}
        {% if name %}
        <li class="nav-item">
         Пользователь: {{ name }}
        </li>
        {% endif %}
        <li>
          {% endwith %} 
        </li>
      </ul>
    </div>
  </nav>
</header>

yatube/templates/includes/name_or_fullname.html
{% if author.get_full_name %}
  {{ author.get_full_name }}
{% else %}
  {{ author }}
{% endif %}

yatube/templates/includes/paginator.html
  {% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation" class="my-5">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page=1"><<</a></li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
              <
            </a>
          </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
              <li class="page-item active">
                <span class="page-link">{{ i }}</span>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
              </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
              >
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
              >>
            </a>
          </li>
        {% endif %}    
      </ul>
    </nav>
  {% endif %} 

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}