yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'


urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.TechView.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_post, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.handler500'

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        help_text='Введите текст',
        verbose_name='Текст поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        'Group',
        blank=True, null=True,
        on_delete=models.SET_NULL,
        related_name='groups',
        verbose_name='Группа',
        help_text='Выбирите название группы'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Группа')
    slug = models.SlugField(unique=True)
    description = models.TextField(verbose_name='Описание группы')

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        related_name='comments',
        on_delete=models.CASCADE)
    text = models.TextField(verbose_name='Текст комментария')
    created = models.DateTimeField(auto_now_add=True)


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE
    )

yatube/posts/forms.py
from django import forms

from posts.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст поста',
            'group': 'Название сообщества',
            'image': 'Изображение'
        }
        help_texts = {
            'text': 'Введите текст поста',
            'group': 'Выбирите группу',
            'image': 'Выберите файл с изображением'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст комментария'
        }
        help_texts = {
            'text': 'Введите текст комментария'
        }

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.views.decorators.cache import cache_page

from posts.forms import PostForm, CommentForm
from .models import Follow, Post, Group, User


POSTS_PER_PAGE = 10


def get_paginator(request, page, num):
    paginator = Paginator(page, num)
    page_numder = request.GET.get('page')
    page_obj: Paginator = paginator.get_page(page_numder)
    return page_obj


@cache_page(60 / 3, key_prefix='page_obj')
def index(request):
    template = 'posts/index.html'
    title = 'Последние обновления на сайте'
    posts = Post.objects.all()
    page_obj = get_paginator(request, posts, POSTS_PER_PAGE)
    context = {
        'page_obj': page_obj,
        'title': title}
    return render(request, template, context)


def group_post(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.groups.all()
    description = group.description
    page_obj = get_paginator(request, posts, POSTS_PER_PAGE)
    title = f'Вы в сообществе {group}'
    context = {
        'description': description,
        'page_obj': page_obj,
        'group': group,
        'title': title}
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    count = posts.count()
    following = author.following.filter(user=request.user.id).exists()
    page_obj = get_paginator(request, posts, POSTS_PER_PAGE)
    context = {
        'following': following,
        'count': count,
        'page_obj': page_obj,
        'author': author
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    author_posts = post.author.posts.all()
    author_name = post.author
    form = CommentForm()
    comments = post.comments.all()
    user = request.user
    count = author_posts.count()
    context = {
        'author_name': author_name,
        'user': user,
        'count': count,
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    user = request.user
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = user
        post.save()
        return redirect('posts:profile', username=user.username)
    form = PostForm()
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    return render(request, 'posts/create_post.html',
                  {'form': form, 'post_id': post_id, 'is_edit': True})


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    title = 'Избранное'
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = get_paginator(request, posts, POSTS_PER_PAGE)
    context = {
        'title': title,
        'page_obj': page_obj
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = get_object_or_404(User, username=username)
    if request.user != user and not user.following.filter(
            user=request.user.id).exists():
        Follow.objects.create(user=request.user, author=user)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    user = get_object_or_404(User, username=username)
    unfollow = get_object_or_404(Follow, user=request.user, author=user)
    unfollow.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}{% if is_edit %}Редактировать пост{% else %}Новый пост{% endif %}{% endblock %}
{% block content %}
{% load user_filters %}
  {% if is_edit %}
    <h1>Редактировать пост</h1>
  {% else %}
    <h1>Новый пост</h1>
  {% endif %}
  <style>
    form, h1, .lead {
      width: 70% !important;
      margin: auto;
    }
  </style>
  <form method="POST" 
    action={% if is_edit %}
             {% url 'posts:post_edit' post_id %}
           {% else %}
             {% url 'posts:post_create' %}
           {% endif %}
    enctype="multipart/form-data"
  >
  {% csrf_token %}
  {% for field in form %}
    <div class="form-group row my-3"
      aria-required="false"
    >
      <label for="{{ field.id_for_label }}">
        {{ field.label }}
          {% if field.field.required %}
            <span class="required text-danger">*</span>
          {% endif %}
      </label>
        {{ field|addclass:'form-control' }} 
    </div>
  {% endfor %}
  {% for field, errors in form.errors.items %}
    {% for error in errors %}
      <p>{{ error }}</p>
    {% endfor %}
  {% endfor %}
    <div class="col-md-6 offset-md-4">
    {% if is_edit %}         
      <button type="submit" class="btn btn-primary">
        Сохранить
      </button>
    {% else %}
      <button type="submit" class="btn btn-primary">
        Добавить
      </button>
    {% endif %}
    </div>
  </form>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
  {% include 'includes/switcher.html' %}
  <div class="container py-5">
      <h3>{{ title }}</h3>
    {% cache 20 index_page page_obj.number %}
    {% for post in page_obj %}
      {% include 'includes/card_author.html' %} 
    {% endfor %}
    {% endcache %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group }}</h1>
    <p>{{ description }}</p>
    {% for post in page_obj %}
      {% include 'includes/card_author.html' %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
  {% include 'includes/switcher.html' %}
    <div class="container py-5">
      {% for post in page_obj %}
        {% include 'includes/card_author.html' %} 
      {% endfor %}
      {% include 'includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}{{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
{% load thumbnail %}
{% load user_filters %}
  <div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
        {% if post.group %}  
          <li class="list-group-item">
            Группа: {{ post.group }}
            <a href={% url 'posts:group_list' post.group.slug %}>
              все записи группы
            </a>
          </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{ author_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ count }}</span>
        </li>
        <li class="list-group-item">
          <a href={% url 'posts:profile' post.author.username %}>
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
    </article>
  </div>
  {% if author_name == user %}
  <a class="btn btn-primary" href={% url 'posts:post_edit' post.id %}>
    редактировать запись
  </a>
  {% endif %}
</div>
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %} 

{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} Профайл пользователя {% include 'includes/name_or_fullname.html' %}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Все посты пользователя {% include 'includes/name_or_fullname.html' %}</h1>
    <p>Всего постов {{ count }}</p>
    {% if request.user.is_authenticated and request.user != author %}
    {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
        Подписаться
      </a>
   {% endif %}
   {% endif %}
    <article>
      {% for post in page_obj %}
        {% include 'includes/card_author.html' %}
    </article>
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}